"use strict";
const bcrypt = require("bcryptjs");
const uuid = require("uuid");
module.exports = {
  up: async (queryInterface, DataTypes) => {
    await queryInterface.bulkInsert(
      "carriers",
      [
        {
          uuid: uuid.v4(),
          code: "s1asd2fta",
          username: "carrier",
          name: "Planasmyrat",
          phone: "+9936a11as11111",
          email: "abc@gmail.com",
          password: await bcrypt.hash("carrier", 12),
          device_token: "this is a fake device token",
          cash: 0,
          tasks_all: 1120,
          tasks_today: 4,
          isExpress: true,
          isBlocked: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "s12ftfsdfa",
          username: "qwertysas",
          name: "Planasmyrat",
          phone: "+9936a11as11111",
          email: "abc@gmail.com",
          password: await bcrypt.hash("carriser", 12),
          device_token: "this is a fake device token",
          cash: 0,
          tasks_all: 80,
          tasks_today: 230,
          isExpress: true,
          isBlocked: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "s12fsdfsdfta",
          username: "qwsdzzsaas",
          name: "Planasmyrat",
          phone: "+9936a11as11111",
          email: "abc@gmail.com",
          password: await bcrypt.hash("carriser", 12),
          device_token: "this is a fake device token",
          cash: 0,
          tasks_all: 8150,
          tasks_today: 22,
          isExpress: false,
          isBlocked: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "s12fjgjta",
          username: "szcxzdcvdxcvas",
          name: "Planasmyrat",
          phone: "+9936a11as11111",
          email: "abc@gmail.com",
          password: await bcrypt.hash("carriser", 12),
          device_token: "this is a fake device token",
          cash: 0,
          tasks_all: 8150,
          tasks_today: 22,
          isExpress: true,
          isBlocked: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "s12fghjgta",
          username: "sghjhgfdxzcaas",
          name: "Planasmyrat",
          phone: "+9936a11as11111",
          email: "abc@gmail.com",
          password: await bcrypt.hash("carriser", 12),
          device_token: "this is a fake device token",
          cash: 0,
          tasks_all: 8150,
          tasks_today: 22,
          isExpress: false,
          isBlocked: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "s7876543zx2cfds12fta",
          username: "fdghjkhgfdsas",
          name: "Planasmyrat",
          phone: "+9936a11as11111",
          email: "abc@gmail.com",
          password: await bcrypt.hash("carriser", 12),
          device_token: "this is a fake device token",
          cash: 0,
          tasks_all: 8150,
          tasks_today: 22,
          isExpress: true,
          isBlocked: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "s12fsfdta",
          username: "oidspsaas",
          name: "Planasmyrat",
          phone: "+9936a11as11111",
          email: "abc@gmail.com",
          password: await bcrypt.hash("carriser", 12),
          device_token: "this is a fake device token",
          cash: 0,
          tasks_all: 8150,
          tasks_today: 22,
          isExpress: false,
          isBlocked: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "s12dfhhgfta",
          username: "aasdsas",
          name: "Planasmyrat",
          phone: "+9936a11as11111",
          email: "abc@gmail.com",
          password: await bcrypt.hash("carriser", 12),
          device_token: "this is a fake device token",
          cash: 0,
          tasks_all: 8150,
          tasks_today: 22,
          isExpress: true,
          isBlocked: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, DataTypes) => {
    await queryInterface.bulkDelete("carriers", null, {});
  },
};
