"use strict";
const bcrypt = require("bcryptjs");
const uuid = require("uuid");
module.exports = {
  up: async (queryInterface, DataTypes) => {
    await queryInterface.bulkInsert(
      "users",
      [
        {
          uuid: uuid.v4(),
          name: "Planyyew Plany",
          phone: "1",
          email: "abc@gmail.com",
          password: await bcrypt.hash("user", 12),
          promos: [1, 2, 1],
          orders_delivered: 0,
          orders_rejected: 0,
          device_token: "this is a fake device token",
          isVerified: true,
          isBlocked: false,
          isSupplier: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          name: "Planysdfsyew Plany",
          phone: "2",
          email: "abc@gmail.com",
          password: await bcrypt.hash("user", 12),
          promos: [2, 2, 1, 1],
          orders_delivered: 0,
          orders_rejected: 0,
          device_token: "this is a fake device token",
          isVerified: true,
          isBlocked: false,
          isSupplier: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          name: "Kyyas Ilmyradov",
          phone: "61064781",
          email: "kyyas.ilmyradov@gmail.com",
          password: await bcrypt.hash("123123", 12),
          promos: [2, 2, 1, 1],
          orders_delivered: 0,
          orders_rejected: 0,
          device_token: "this is a fake device token",
          isVerified: true,
          isBlocked: false,
          isSupplier: false,
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "5223",
          name: "Plannyyyew",
          phone: "61270943",
          email: "abc@gmail.com",
          company_name: "apple",
          promos: [1, 2, 1],
          orders_delivered: 0,
          orders_rejected: 0,
          device_token: "this is a fake device token",
          isBlocked: false,
          isVerified: true,
          isSupplier: true,
          password: await bcrypt.hash("supplier", 12),
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
        {
          uuid: uuid.v4(),
          code: "5224",
          name: "Planmyradow",
          phone: "61064782",
          email: "abc@as.com",
          company_name: "tesla",
          promos: [1, 2, 1],
          orders_delivered: 0,
          orders_rejected: 0,
          device_token: "this is a fake device token",
          isBlocked: false,
          isVerified: true,
          isSupplier: true,
          password: await bcrypt.hash("supplier", 12),
          createdAt: DataTypes.fn("now"),
          updatedAt: DataTypes.fn("now"),
        },
      ],
      {}
    );
  },

  down: async (queryInterface, DataTypes) => {
    await queryInterface.bulkDelete("users", null, {});
  },
};
